### ISSUE TITLE
Current version has troubles with EAGLE UmlYangTools project 

### ISSUE THREAD

**Issue by rvilalta** [OpenNetworkingFoundation/ONFOpenTransport#31]
Dear Hui,

Please check this current devel version of TapiModule.uml:

https://raw.githubusercontent.com/OpenNetworkingFoundation/ONFOpenTransport/develop/TransportAPI/UML/TapiModule.uml

There are problems with Context and Topology. What do you recomment?

Tapi-ObjectClasses.yang:324: error: Tapi-ObjectClasses:Context in the path for _lowerConnection at Tapi-ObjectClasses.yang:48 (at Tapi-ObjectClasses.yang:321) is not found

Tapi-ObjectClasses.yang:75: error: Tapi-Interfaces-TopologyService:Topology in the path for _aggregatedNodeEdgePoint at Tapi-Interfaces-TopologyService.yang:16 (at Tapi-ObjectClasses.yang:72) is not found

Thanks,
Ricard

**Comment by zhangguoying2015** [comment]
Dear Ricard,

Sorry for the late reply. I translate the uml file in your message. And use pyang tree and json_schema command, no error is reported. Can you please let me know how you get the errors?

**Comment by HuiDingCATR** [comment]
Dear Ricard,

Sorry for the late reply. I translate the uml file in your message. And use pyang tree and json_schema command, no error is reported. Can you please let me know how you get the errors?
